name: "Continuous Integration"

on:
    pull_request:
    push:

jobs:
    phpunit:
        name: Test Suite
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.1, 7.2, 7.3, 7.4, 8.0]
        steps:
            - uses: actions/checkout@v2
            - name: Install PHP ${{ matrix.php }}
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  ini-values: "memory_limit=-1, phar.readonly=0"
                  php-version: ${{ matrix.php }}

            - name: "Determine composer cache directory"
              id: "determine-composer-cache-directory"
              run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

            - name: "Cache dependencies installed with composer"
              uses: "actions/cache@v1"
              with:
                  path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
                  key: "php-${{ matrix.php }}-ci"
                  restore-keys: "php-${{ matrix.php }}"

            - name: "Install dependencies"
              run: composer update --no-progress -o --prefer-dist

            - name: "Run PHPUnit"
              run: ./vendor/bin/phpunit

            - name: "Run PHPStan"
              run: ./vendor/bin/phpstan analyze lib test --level=4
